name: moodiary
description: "A fully open source cross-platform diary app written by flutter and rust."
publish_to: 'none'
version: 2.7.3+74

environment:
  sdk: '>=3.7.0'
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter

  get: 5.0.0-release-candidate-9.3.2
  dio: 5.8.0+1
  path: 1.9.1
  path_provider: 2.1.5
  calendar_date_picker2: 2.0.0
  logger: 2.5.0
  flutter_drawing_board: 0.9.8
  flutter_displaymode: 0.6.0
  fl_chart: 0.71.0
  file_picker: 10.1.2
  local_auth: 2.3.0
  local_auth_android: 1.0.48
  permission_handler: 12.0.0+1
  image_picker: 1.1.2
  device_info_plus: 11.3.3
  package_info_plus: 8.3.0
  uuid: 4.5.1
  flutter_quill: 11.2.0
  share_plus: 10.1.4
  url_launcher: 6.3.1
  archive: 4.0.5
  crypto: 3.0.6
  markdown_widget: 2.3.2+6
  flutter_colorpicker: 1.1.0
  geolocator: 14.0.0
  shared_preferences: 2.5.3
  isar: 4.0.0-dev.14
  isar_flutter_libs:
    git:
      url: https://github.com/ZhuJHua/isar
      path: packages/isar_flutter_libs
  cached_network_image: 3.4.1
  audioplayers: 6.4.0
  record: 6.0.0
  duration: 4.0.3
  dynamic_color: 1.7.0
  supabase_flutter: 2.8.4
  bitsdojo_window: 0.1.6
  intl: 0.19.0
  collection: 1.19.1
  cupertino_icons: 1.0.8
  font_awesome_flutter: 10.8.0
  tflite_flutter: 0.11.0
  sliver_tools: 0.2.12
  lottie: 3.3.1
  media_kit: 1.2.0
  media_kit_video: 1.3.0
  media_kit_libs_windows_video: 1.0.11
  flutter_adaptive_scaffold: 0.3.2
  cross_file: 0.3.4+2
  fc_native_video_thumbnail: 0.17.2
  flutter_map: 7.0.2
  flutter_map_cache: 2.0.0
  flutter_map_marker_cluster: 1.4.0
  http_cache_hive_store: 5.0.1
  latlong2: 0.9.1
  shelf: 1.4.2
  shelf_multipart: 2.0.1
  waterfall_flow: 3.1.1
  smooth_page_indicator: 1.2.1
  unicons: 3.0.0
  encrypt: 5.0.3
  faker: 2.2.0
  flutter_rust_bridge: 2.9.0
  syncfusion_flutter_sliders: 29.1.38
  flutter_quill_extensions: 11.0.0
  connectivity_plus: 6.1.3
  image_picker_android: 0.8.12+22
  video_player_media_kit: 1.0.6
  video_player: 2.9.5
  chewie: 1.11.1
  flutter_markdown: 0.7.7
  image_picker_platform_interface: 2.10.1
  flutter_image_compress: 2.4.0
  mime: 2.0.0
  auto_size_text_field: 2.2.4
  webdav_client: 1.2.2
  confetti: 0.8.0
  flutter_native_splash: 2.4.6
  gal: 2.3.1
  network_info_plus: 6.1.3
  scrollable_positioned_list: 0.3.8
  flutter_localizations:
    sdk: flutter
  moodiary_rust:
    path: rust_builder
  modal_bottom_sheet: 3.0.0
  tutorial_coach_mark: 1.3.0
  adaptive_dialog: 2.4.1
  flutter_inappwebview: 6.1.5
  markdown: 7.3.0
  flutter_highlight: 0.7.0
  synchronized: 3.3.1
  flutter_secure_storage: 9.2.4
  fpdart: 2.0.0-dev.3
  rxdart: 0.28.0
  minio: 3.5.7
  page_transition: 2.2.1
  dismissible_page: 1.0.2
  photo_view: 0.15.0
  dartx: 1.2.0
  material_color_utilities: 0.11.1
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  audioplayers_android_exo: 0.1.2
  scrollview_observer: 1.26.0
  flutter_smart_dialog: 4.9.8+7
  substring_highlight: 1.0.33
  qr_flutter: 4.1.0
  mobile_scanner: 7.0.0-beta.9
  throttling: 2.0.1
  gap: 3.0.1
  flutter_cache_manager: 3.4.1
  hive_ce: 2.10.1
  hive_ce_flutter: 2.2.0
  flutter_modular: 6.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.15
  flutter_launcher_icons: 0.14.3
  msix: 3.16.8
  flutter_lints: 5.0.0
  riverpod_generator: 2.6.3
  json_serializable: 6.9.0
  flutter_gen: 5.10.0
  flutter_gen_runner: 5.10.0



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/light/light_foreground.png"
  adaptive_icon_monochrome: "assets/icon/light/light_foreground.png"
  image_path_ios_dark_transparent: "assets/icon/dark/dark_foreground.png"
  image_path_ios_tinted_grayscale: "assets/icon/light/light_foreground.png"
  desaturate_tinted_to_grayscale_ios: true
  image_path: "assets/icon/light/light_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 26
  windows:
    generate: true
    image_path: "assets/icon/light/light_icon_desktop.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon/light/light_icon_desktop.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/light/light_splash_icon.png
  color_dark: "#000000"
  image_dark: assets/icon/dark/dark_splash_icon.png

  android_12:
    image: assets/icon/light/light_splash_icon.png
    color: "#ffffff"
    image_dark: assets/icon/dark/dark_splash_icon.png
    color_dark: "#000000"
  fullscreen: true
  web: false

flutter:
  generate: true
  fonts:
    - family: qweather
      fonts:
        - asset: assets/fonts/qweather-icons.ttf

  assets:
    - assets/icon/dark/
    - assets/icon/light/
    - assets/lottie/
    - res/sponsor/
    - assets/tflite/

  uses-material-design: true

msix_config:
  display_name: Moodiary
  identity_name: JHZhu.Moodiary
  publisher: CN=8FC154B5-951B-4B96-B1CA-5A8A86B49C11
  publisher_display_name: JH Zhu
  capabilities: internetClient, location, microphone
  logo_path: assets/icon/light/light_icon_desktop.png
  store: true