# This is copied from Cargokit (which is the official way to use it currently)
# Details: https://fzyzcjy.github.io/flutter_rust_bridge/manual/integrate/builtin

name: build_tool
description: Cargokit build_tool. Facilitates the build of Rust crate during Flutter application build.
publish_to: none
version: 1.0.0
resolution: workspace

environment:
  sdk: '>=3.7.0'

# Add regular dependencies here.
dependencies:
  # these are pinned on purpose because the bundle_tool_runner doesn't have
  # pubspec.lock. See run_build_tool.sh
  logging: 1.3.0
  path: 1.9.1
  version: 3.0.2
  collection: 1.19.1
  ed25519_edwards: 0.3.1
  hex: 0.2.0
  yaml: 3.1.3
  source_span: 1.10.1
  github: 9.24.0
  args: 2.7.0
  crypto: 3.0.6
  convert: 3.1.2
  http: 1.3.0
  toml: 0.16.0

dev_dependencies:
  lints: 5.1.1
  test: 1.25.15
